apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-pod # Base POD name
  namespace: sales-system
spec:
  selector:
    matchLabels:
      app: sales # Selector for POD name search.
  template:
    metadata:
      labels:
        app: sales
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: sales-api
        image: sales-api-image
        ports:
          - name: sales-api
            containerPort: 7000
          - name: sales-api-debug
            containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: sales
  ports:
    - name: sales-api
      port: 7000
      targetPort: sales-api
    - name: sales-api-debug
      port: 7001
      targetPort: sales-api-debug
